package com.scsk.constants;
/**
 * Application Info
 */
public class ApplicationKeys {
    /** insightIndex.login.login_getUserInfo=insightIndex/login_getUserInfo */
    public static final String INSIGHTINDEX_LOGIN_LOGIN_GETUSERINFO = "insightIndex/login_getUserInfo";
    /** insightIndex.accountMnt.searchByUserId_UserInfo=insightIndex/accountMnt_searchByUserId_UserInfo */
    public static final String INSIGHTINDEX_ACCOUNTMNT_SEARCHBYUSERID_USERINFO = "insightIndex/accountMnt_searchByUserId_UserInfo";
    /** insightIndex.accountMnt.searchByFacebookId_UserInfo=insightIndex/accountMnt_searchByFacebookId_UserInfo */
    public static final String INSIGHTINDEX_ACCOUNTMNT_SEARCHBYFACEBOOKID_USERINFO = "insightIndex/accountMnt_searchByFacebookId_UserInfo";
    /** insightIndex.accountMnt.serachByEmail.UserInfo=insightIndex/accountMnt_searchByEmail_UserInfo */
    public static final String INSIGHTINDEX_ACCOUNTMNT_SERACHBYEMAIL_USERINFO = "insightIndex/accountMnt_searchByEmail_UserInfo";
    /** insightIndex.accountAppList.accountAppListPushRecord=insightIndex/accountAppListPushRecord */
    public static final String INSIGHTINDEX_ACCOUNTAPPLIST_ACCOUNTAPPLISTPUSHRECORD = "insightIndex/accountAppListPushRecord";
    /** insightIndex.function.function_searchInfo=insightIndex/function_searchInfo */
    public static final String INSIGHTINDEX_FUNCTION_FUNCTION_SEARCHINFO = "insightIndex/function_searchInfo";
    /** insightIndex.user.user_searchInfo=insightIndex/user_searchInfo */
    public static final String INSIGHTINDEX_USER_USER_SEARCHINFO = "insightIndex/user_searchInfo";
    /** insightIndex.user.accountAppBatch=insightIndex/accountAppBatch */
    public static final String INSIGHTINDEX_USER_ACCOUNTAPPBATCH = "insightIndex/accountAppBatch";
    /** insightIndex.store.storeATM_searchInfo=insightIndex/storeATM_searchInfo */
    public static final String INSIGHTINDEX_STORE_STOREATM_SEARCHINFO = "insightIndex/storeATM_searchInfo";
    /** insightIndex.user.searchByUserID_userInfo=insightIndex/user_searchByUserID_userInfo */
    public static final String INSIGHTINDEX_USER_SEARCHBYUSERID_USERINFO = "insightIndex/user_searchByUserID_userInfo";
    /** insightIndex.user.pwsHistory_searchInfo=insightIndex/user_pwsHistory_searchInfo */
    public static final String INSIGHTINDEX_USER_PWSHISTORY_SEARCHINFO = "insightIndex/user_pwsHistory_searchInfo";
    /** insightIndex.assistant.searchByUserId_ASSISTANTCHAT=insightIndex/assistant_searchByUserId_ASSISTANTCHAT */
    public static final String INSIGHTINDEX_ASSISTANT_SEARCHBYUSERID_ASSISTANTCHAT = "insightIndex/assistant_searchByUserId_ASSISTANTCHAT";
    /** insightIndex.accountApp.searchByUserId_AccountApplication=insightIndex/accountApp_searchByUserId_AccountApplication */
    public static final String INSIGHTINDEX_ACCOUNTAPP_SEARCHBYUSERID_ACCOUNTAPPLICATION = "insightIndex/accountApp_searchByUserId_AccountApplication";
    /** insightIndex.actionLog_searchByUserId_Info=insightIndex/actionLog_searchByUserId_Info */
    public static final String INSIGHTINDEX_ACTIONLOG_SEARCHBYUSERID_INFO = "insightIndex/actionLog_searchByUserId_Info";
    /** insightIndex.contentsApp_searchInfo=insightIndex/contentsApp_searchInfo */
    public static final String INSIGHTINDEX_CONTENTSAPP_SEARCHINFO = "insightIndex/contentsApp_searchInfo";
    /** insightIndex.contentsType_searchInfo=insightIndex/contentsType_searchInfo */
    public static final String INSIGHTINDEX_CONTENTSTYPE_SEARCHINFO = "insightIndex/contentsType_searchInfo";
    /** insightIndex.contents_searchInfo=insightIndex/contents_searchInfo */
    public static final String INSIGHTINDEX_CONTENTS_SEARCHINFO = "insightIndex/contents_searchInfo";
    /** insightIndex.contents_removeByAppCD=insightIndex/contents_removeByAppCD */
    public static final String INSIGHTINDEX_CONTENTS_REMOVEBYAPPCD = "insightIndex/contents_removeByAppCD";
    /** insightIndex.contentsType_removeByAppCD=insightIndex/contentsType_removeByAppCD */
    public static final String INSIGHTINDEX_CONTENTSTYPE_REMOVEBYAPPCD = "insightIndex/contentsType_removeByAppCD";
    /** insightIndex.contents_removeByAppCDAndTypeCD=insightIndex/contents_removeByAppCDAndTypeCD */
    public static final String INSIGHTINDEX_CONTENTS_REMOVEBYAPPCDANDTYPECD = "insightIndex/contents_removeByAppCDAndTypeCD";
    /** insightIndex.account.searchByAccountAppSeq_AgreeDate=insightIndex/account_searchByAccountAppSeq_AgreeDate */
    public static final String INSIGHTINDEX_ACCOUNT_SEARCHBYACCOUNTAPPSEQ_AGREEDATE = "insightIndex/account_searchByAccountAppSeq_AgreeDate";
    /** insightIndex.message.searchByPushTitlelOid_MsgOpenStatus=insightIndex/message_searchByPushTitlelOid_MsgOpenStatus */
    public static final String INSIGHTINDEX_MESSAGE_SEARCHBYPUSHTITLELOID_MSGOPENSTATUS = "insightIndex/message_searchByPushTitlelOid_MsgOpenStatus";
    /** insightIndex.statusModify_searchInfo=insightIndex/statusModify_searchInfo */
    public static final String INSIGHTINDEX_STATUSMODIFY_SEARCHINFO = "insightIndex/statusModify_searchInfo";
    /** insightView.accountAppList.accountAppList=accountAppList */
    public static final String INSIGHTVIEW_ACCOUNTAPPLIST_ACCOUNTAPPLIST = "accountAppList";
    /** insightView.accountAppList.accountAppBatch=accountAppBatch */
    public static final String INSIGHTVIEW_ACCOUNTAPPLIST_ACCOUNTAPPBATCH = "accountAppBatch";
    /** insightView.accountAppList.accountAppBak=accountAppBak */
    public static final String INSIGHTVIEW_ACCOUNTAPPLIST_ACCOUNTAPPBAK = "accountAppBak";
    /** insightView.accountAppList.accountApp=accountApp */
    public static final String INSIGHTVIEW_ACCOUNTAPPLIST_ACCOUNTAPP = "accountApp";
    /** insightView.accountAppBatch.accountSum=accountSum */
    public static final String INSIGHTVIEW_ACCOUNTAPPBATCH_ACCOUNTSUM = "accountSum";
    /** insightView.storeATMList.storeATMList=storeATMList */
    public static final String INSIGHTVIEW_STOREATMLIST_STOREATMLIST = "storeATMList";
    /** insightView.functionList.functionList=functionList */
    public static final String INSIGHTVIEW_FUNCTIONLIST_FUNCTIONLIST = "functionList";
    /** insightView.authorityList.authorityList=authorityList */
    public static final String INSIGHTVIEW_AUTHORITYLIST_AUTHORITYLIST = "authorityList";
    /** insightView.userList.userList=userList */
    public static final String INSIGHTVIEW_USERLIST_USERLIST = "userList";
    /** insightView.userInfoList.userInfoList=userInfoList */
    public static final String INSIGHTVIEW_USERINFOLIST_USERINFOLIST = "userInfoList";
    /** insightView.yamagataUserInfoList.userInfoList=userInfo */
    public static final String INSIGHTVIEW_YAMAGATAUSERINFOLIST_USERINFOLIST = "userInfo";
    /** insightView.userInfoList.userInfoKeyList=userInfoKeyList */
    public static final String INSIGHTVIEW_USERINFOLIST_USERINFOKEYLIST = "userInfoKeyList";
    /** insightView.ContactUs.ContactUsList=contactUsList */
    public static final String INSIGHTVIEW_CONTACTUS_CONTACTUSLIST = "contactUsList";
    /** insightView.accountAppSeqList.accountAppSeqList=accountAppSeqList */
    public static final String INSIGHTVIEW_ACCOUNTAPPSEQLIST_ACCOUNTAPPSEQLIST = "accountAppSeqList";
    /** insightView.pushRecordList.pushRecordList=pushRecordList */
    public static final String INSIGHTVIEW_PUSHRECORDLIST_PUSHRECORDLIST = "pushRecordList";
    /** insightView.assistantChatList.assistantChatList=assistantChatList */
    public static final String INSIGHTVIEW_ASSISTANTCHATLIST_ASSISTANTCHATLIST = "assistantChatList";
    /** insightView.agreedOperationDateList.agreedOperationDateList=agreedOperationDateList */
    public static final String INSIGHTVIEW_AGREEDOPERATIONDATELIST_AGREEDOPERATIONDATELIST = "agreedOperationDateList";
    /** insightView.lanuchAgreeList.lanuchAgreeList=lanuchAgreeList */
    public static final String INSIGHTVIEW_LANUCHAGREELIST_LANUCHAGREELIST = "lanuchAgreeList";
    /** insightView.imageList.imageList=imageList */
    public static final String INSIGHTVIEW_IMAGELIST_IMAGELIST = "imageList";
    /** insightView.pushMessageList.msgTitle=msgTitle */
    public static final String INSIGHTVIEW_PUSHMESSAGELIST_MSGTITLE = "msgTitle";
    /** insightView.pwdHistoryList.pwdHistoryList=pwdHistoryList */
    public static final String INSIGHTVIEW_PWDHISTORYLIST_PWDHISTORYLIST = "pwdHistoryList";
    /** insightView.userActionLogList.userActionLogList=userActionLogList */
    public static final String INSIGHTVIEW_USERACTIONLOGLIST_USERACTIONLOGLIST = "userActionLogList";
    /** insightView.userMigrationList.userMigrationList=userMigrationList */
    public static final String INSIGHTVIEW_USERMIGRATIONLIST_USERMIGRATIONLIST = "userMigrationList";
    /** insightView.batchList.batchList=batchList */
    public static final String INSIGHTVIEW_BATCHLIST_BATCHLIST = "batchList";
    /** insightView.actionLogList.actionLogList=ActionLogList */
    public static final String INSIGHTVIEW_ACTIONLOGLIST_ACTIONLOGLIST = "ActionLogList";
    /** insightView.imageFile.imageFile=imageFile */
    public static final String INSIGHTVIEW_IMAGEFILE_IMAGEFILE = "imageFile";
    /** insightView.masterData.masterData=storeATMDataFile */
    public static final String INSIGHTVIEW_MASTERDATA_MASTERDATA = "storeATMDataFile";
    /** insightView.storeATMDataList.storeATMDataList=storeATMDataList */
    public static final String INSIGHTVIEW_STOREATMDATALIST_STOREATMDATALIST = "storeATMDataList";
    /** insightView.contentsAppList.contentsAppList=contentsAppList */
    public static final String INSIGHTVIEW_CONTENTSAPPLIST_CONTENTSAPPLIST = "contentsAppList";
    /** insightView.contentsTypeList.contentsTypeList=contentsTypeList */
    public static final String INSIGHTVIEW_CONTENTSTYPELIST_CONTENTSTYPELIST = "contentsTypeList";
    /** insightView.contentsList.contentsList=contentsList */
    public static final String INSIGHTVIEW_CONTENTSLIST_CONTENTSLIST = "contentsList";
    /** insightView.agreeDate.agreeDate=agreeDate */
    public static final String INSIGHTVIEW_AGREEDATE_AGREEDATE = "agreeDate";
    /** insightView.iyoUserInfoList.userInfoList=userInfo */
    public static final String INSIGHTVIEW_IYOUSERINFOLIST_USERINFOLIST = "userInfo";
    /** insightView.followInfoList.followInfo_userId=followInfo_userId */
    public static final String INSIGHTVIEW_FOLLOWINFOLIST_FOLLOWINFO_USERID = "followInfo_userId";
    /** insightView.clipInfoList.clipInfo_userId=clipInfo_userId */
    public static final String INSIGHTVIEW_CLIPINFOLIST_CLIPINFO_USERID = "clipInfo_userId";
    /** insightView.accountDocumentList.accountDocumentList=accountDocumentList */
    public static final String INSIGHTVIEW_ACCOUNTDOCUMENTLIST_ACCOUNTDOCUMENTLIST = "accountDocumentList";
    /** insightview.account.accountNumber=userInfo_accountNumber */
    public static final String INSIGHTVIEW_ACCOUNT_ACCOUNTNUMBER = "userInfo_accountNumber";
    /** insightview.push.pushRirekiTorihikiData=pushRirekiTorihikiData */
    public static final String INSIGHTVIEW_PUSH_PUSHRIREKITORIHIKIDATA = "pushRirekiTorihikiData";
    /** insightView.accountLoanList.accountLoanList=accountLoanList */
    public static final String INSIGHTVIEW_ACCOUNTLOANLIST_ACCOUNTLOANLIST = "accountLoanList";
    /** insightView.statusModify_Loan.statusModify_Loan=statusModify_Loan */
    public static final String INSIGHTVIEW_STATUSMODIFY_LOAN_STATUSMODIFY_LOAN = "statusModify_Loan";
    /** insightView.documentPushRecord.documentPushRecord=documentPushRecord */
    public static final String INSIGHTVIEW_DOCUMENTPUSHRECORD_DOCUMENTPUSHRECORD = "documentPushRecord";
    /** insightView.documentPushDetail.documentPushDetail=documentPushDetail */
    public static final String INSIGHTVIEW_DOCUMENTPUSHDETAIL_DOCUMENTPUSHDETAIL = "documentPushDetail";
    /** insightView.documentRecordList.documentRecordList=documentRecordList */
    public static final String INSIGHTVIEW_DOCUMENTRECORDLIST_DOCUMENTRECORDLIST = "documentRecordList";
    /** insightView.documentStatusModify.documentStatusModify=documentStatusModify */
    public static final String INSIGHTVIEW_DOCUMENTSTATUSMODIFY_DOCUMENTSTATUSMODIFY = "documentStatusModify";
    /** insightView.imageAccount.imageAccount=imageAccount */
    public static final String INSIGHTVIEW_IMAGEACCOUNT_IMAGEACCOUNT = "imageAccount";
    /** insightView.imageLoan.imageLoan=imageLoan */
    public static final String INSIGHTVIEW_IMAGELOAN_IMAGELOAN = "imageLoan";
    /** insightView.imageDocument.imageDocument=imageDocument */
    public static final String INSIGHTVIEW_IMAGEDOCUMENT_IMAGEDOCUMENT = "imageDocument";
    /** insightView.statusModify.statusModify=statusModify */
    public static final String INSIGHTVIEW_STATUSMODIFY_STATUSMODIFY = "statusModify";
    /** insightView.globalList.globalList=globalList */
    public static final String INSIGHTVIEW_GLOBALLIST_GLOBALLIST = "globalList";
    /** insightView.msgOpenStatus.msgOpenStatus=msgOpenStatus */
    public static final String INSIGHTVIEW_MSGOPENSTATUS_MSGOPENSTATUS = "msgOpenStatus";
    /** insightView.msgOpenStatus.msgOpenStatus_pushTitlelOid=msgOpenStatus_pushTitlelOid */
    public static final String INSIGHTVIEW_MSGOPENSTATUS_MSGOPENSTATUS_PUSHTITLELOID = "msgOpenStatus_pushTitlelOid";
    /** insightView.msgOpenStatus.msgOpenStatus_userId=msgOpenStatus_userId */
    public static final String INSIGHTVIEW_MSGOPENSTATUS_MSGOPENSTATUS_USERID = "msgOpenStatus_userId";
    /** report.resources.path=/resources */
    public static final String REPORT_RESOURCES_PATH = "/resources";
    /** report.jasper.path=/jasper/ */
    public static final String REPORT_JASPER_PATH = "/jasper/";
    /** report.protected.path=/protected */
    public static final String REPORT_PROTECTED_PATH = "/protected";
    /** report.temp.path=/temp/ */
    public static final String REPORT_TEMP_PATH = "/temp/";
    /** report.excel.path=/WEB-INF/Report_Template */
    public static final String REPORT_EXCEL_PATH = "/WEB-INF/Report_Template";
    /** report.html.path=/temp/html */
    public static final String REPORT_HTML_PATH = "/temp/html";
    /** mail.resources.path=/resources/mailTemplate */
    public static final String MAIL_RESOURCES_PATH = "/resources/mailTemplate";
    /** contents.path=/images/contents */
    public static final String CONTENTS_PATH = "/images/contents";
    /** account001_report=Account001_Report.jasper */
    public static final String ACCOUNT001_REPORT = "Account001_Report.jasper";
    /** accountAppList001_report=accountAppProgress_Report.jasper */
    public static final String ACCOUNTAPPLIST001_REPORT = "accountAppProgress_Report.jasper";
    /** accountAppList002_report=personalImage_Report.jasper */
    public static final String ACCOUNTAPPLIST002_REPORT = "personalImage_Report.jasper";
    /** accountAppList003_report=personalInformationManagement_Report.jasper */
    public static final String ACCOUNTAPPLIST003_REPORT = "personalInformationManagement_Report.jasper";
    /** accountAppList004_report=accountAppList_Report.jasper */
    public static final String ACCOUNTAPPLIST004_REPORT = "accountAppList_Report.jasper";
    /** accountAppList005_report=accountAppListErr_Report.jasper */
    public static final String ACCOUNTAPPLIST005_REPORT = "accountAppListErr_Report.jasper";
    /** accountAppList101_report=\u53E3\u5EA7\u958B\u8A2D\u7533\u8FBC\u53D7\u4ED8\u9032\u6357\u7BA1\u7406\u8868 */
    public static final String ACCOUNTAPPLIST101_REPORT = "\u53E3\u5EA7\u958B\u8A2D\u7533\u8FBC\u53D7\u4ED8\u9032\u6357\u7BA1\u7406\u8868";
    /** accountAppList102_report=\u78BA\u8A8D\u66F8\u985E\u753B\u50CF */
    public static final String ACCOUNTAPPLIST102_REPORT = "\u78BA\u8A8D\u66F8\u985E\u753B\u50CF";
    /** accountAppList103_report=\u500B\u4EBA\u60C5\u5831\u7BA1\u7406\u8868 */
    public static final String ACCOUNTAPPLIST103_REPORT = "\u500B\u4EBA\u60C5\u5831\u7BA1\u7406\u8868";
    /** accountAppList104_report=sumaho_data */
    public static final String ACCOUNTAPPLIST104_REPORT = "sumaho_data";
    /** accountAppList105_report=\u53E3\u5EA7\u7533\u8FBC\u5931\u6557\u30C7\u30FC\u30BF\u306E\u30A8\u30E9\u30FC\u60C5\u5831 */
    public static final String ACCOUNTAPPLIST105_REPORT = "\u53E3\u5EA7\u7533\u8FBC\u5931\u6557\u30C7\u30FC\u30BF\u306E\u30A8\u30E9\u30FC\u60C5\u5831";
    /** useUserList101_report=\u5229\u7528\u30E6\u30FC\u30B6\u30FC\u60C5\u5831\u7BA1\u7406\u8868 */
    public static final String USEUSERLIST101_REPORT = "\u5229\u7528\u30E6\u30FC\u30B6\u30FC\u60C5\u5831\u7BA1\u7406\u8868";
    /** useUserList102_report=\u672A\u914D\u4FE1\u53E3\u5EA7\u756A\u53F7 */
    public static final String USEUSERLIST102_REPORT = "\u672A\u914D\u4FE1\u53E3\u5EA7\u756A\u53F7";
    /** useUserDownloadList101_report=\u30C6\u30FC\u30DE\u60C5\u5831\u7BA1\u7406\u8868 */
    public static final String USEUSERDOWNLOADLIST101_REPORT = "\u30C6\u30FC\u30DE\u60C5\u5831\u7BA1\u7406\u8868";
    /** useUserDownloadList102_report=\u30AF\u30EA\u30C3\u30D7\u60C5\u5831\u7BA1\u7406\u8868 */
    public static final String USEUSERDOWNLOADLIST102_REPORT = "\u30AF\u30EA\u30C3\u30D7\u60C5\u5831\u7BA1\u7406\u8868";
    /** userList001_report=\u30E6\u30FC\u30B6\u30FC\u4E00\u89A7\u8868 */
    public static final String USERLIST001_REPORT = "\u30E6\u30FC\u30B6\u30FC\u4E00\u89A7\u8868";
    /** userList002_report=\u64CD\u4F5C\uFF0F\u884C\u52D5\u30ED\u30B0\u8868 */
    public static final String USERLIST002_REPORT = "\u64CD\u4F5C\uFF0F\u884C\u52D5\u30ED\u30B0\u8868";
    /** insightview_uploadfile_uploadfile=htmlPdfFile */
    public static final String INSIGHTVIEW_UPLOADFILE_UPLOADFILE = "htmlPdfFile";
    /** accountAppList07_report=telDentificationResults_Report.jasper */
    public static final String ACCOUNTAPPLIST07_REPORT = "telDentificationResults_Report.jasper";
    /** accountAppList06_report=ipDentificationResults_Report.jasper */
    public static final String ACCOUNTAPPLIST06_REPORT = "ipDentificationResults_Report.jasper";
    /** yamagataAccountAppList01_report=yamagataTelDentificationResults_Report.jasper */
    public static final String YAMAGATAACCOUNTAPPLIST01_REPORT = "yamagataTelDentificationResults_Report.jasper";
    /** accountAppList106_report=IP\u30A2\u30C9\u30EC\u30B9\u9451\u5B9A\u7D50\u679C */
    public static final String ACCOUNTAPPLIST106_REPORT = "IP\u30A2\u30C9\u30EC\u30B9\u9451\u5B9A\u7D50\u679C";
    /** accountAppList107_report=\u96FB\u8A71\u756A\u53F7\u9451\u5B9A\u7D50\u679C */
    public static final String ACCOUNTAPPLIST107_REPORT = "\u96FB\u8A71\u756A\u53F7\u9451\u5B9A\u7D50\u679C";
    /** accountAppList108_report=TempOpenAccount.xlsx */
    public static final String ACCOUNTAPPLIST108_REPORT = "TempOpenAccount.xlsx";
    /** generalPurpose_outPut_csv=キャンペン_申込ユーザー情報_ */
    public static final String GENERALPURPOSE_OUTPUT_CSV = "キャンペン_申込ユーザー情報_";
}
