package com.scsk.model;

/**
 * ドキュメントタイプの列挙
 * 
 * @author ws
 *
 */
public enum DocTypeEnum {
    USERINFO, AGREEDOPERATIONDATE, IMAGE, ACCOUNTAPPSEQ,
    ACCOUNTAPPLICATION, APPSETTING,
    CONTENTS_APP, CONTENTS, STOREATMINFO, VERSIONDOC,
    STATUS_MODIFY, PUSH_RECORD, PUSH_DETAIL,
    MSG_DETAIL, MSG_OPENSTATUS, MSG_TITLE, GLOBAL_DOC,ACCOUNT_LOAN
}
